services:
  server:
    build: .
    container_name: hybrid_pqc_server
    command: ["python", "-m", "src.server.server_app"]
    ports:
      - "9000:9000"

  client:
    build: .
    container_name: hybrid_pqc_client
    depends_on:
      - server
    command: ["python", "-m", "src.client.client_app"]
